import { Router } from 'express';
import { login, register } from '../controllers/authController';
import { getCategories, createCategory, deleteCategory } from '../controllers/categoryController';
import { getSubcategories, createSubcategory, deleteSubcategory } from '../controllers/subcategoryController';
import { getSummaries, getSummaryById, createSummary, updateSummary, deleteSummary, upload } from '../controllers/summaryController';
import { getSimulations, createSimulation, deleteSimulation } from '../controllers/simulationController';
import { authMiddleware, adminOnly } from '../middlewares/auth';
const router = Router();
router.post('/auth/register', register);
router.post('/auth/login', login);
router.get('/categories', authMiddleware, getCategories);
router.post('/categories', authMiddleware, adminOnly, createCategory);
router.delete('/categories/:id', authMiddleware, adminOnly, deleteCategory);
router.get('/categories/:categoryId/subcategories', authMiddleware, getSubcategories);
router.post('/subcategories', authMiddleware, adminOnly, createSubcategory);
router.delete('/subcategories/:id', authMiddleware, adminOnly, deleteSubcategory);
router.get('/subcategories/:subcategoryId/summaries', authMiddleware, getSummaries);
router.get('/summaries/:id', authMiddleware, getSummaryById);
router.post('/summaries', authMiddleware, adminOnly, upload.single('image'), createSummary);
router.put('/summaries/:id', authMiddleware, adminOnly, updateSummary);
router.delete('/summaries/:id', authMiddleware, adminOnly, deleteSummary);
router.get('/categories/:categoryId/simulations', authMiddleware, getSimulations);
router.post('/simulations', authMiddleware, adminOnly, createSimulation);
router.delete('/simulations/:id', authMiddleware, adminOnly, deleteSimulation);
export default router;
